### ISSUE TITLE
hi sunny issue  after this i follow 2.5videos of yours tried can you sort it please

### ISSUE THREAD

**Issue by Manothegamer** [c17hawke/dvc-project-template#1]
windows 10, vscode
i followed all your steps everthing was ok until dvc repro

$ dvc repro
Running stage 'get_data':
> python src\stage_01_get_data.py --config=configs\config.yaml
list of the folders:   0%|                                                                               | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src\stage_01_get_data.py", line 41, in <module>
    get_data(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src\stage_01_get_data.py", line 29, in get_data
    create_directories([local_data_dir])
  File "e:\dl_projects\dvc_tf\dvc-cnn-tf-pipelne-demo\src\utils\common.py", line 24, in create_directories
    for dir_path in dir_paths:
NameError: name 'dir_paths' is not defined
ERROR: failed to reproduce 'get_data': failed to run: python src\stage_01_get_data.py --config=configs\config.yaml, exited with 
1
(E:Mon May 02l_projectsMon May 02vc_tf\DVC-CNN-TF-pipelne-demov)

**Comment by c17hawke** [comment]
@Manothegamer can you share the link to your codebase. Because as per the log you shared I didn't create any variable by the name `dir_paths` in the `common` utils file.
